/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MyBillboardsRouteImport } from './routes/my-billboards'
import { Route as BillboardsIdRouteImport } from './routes/billboards.$id'
import { Route as BillboardsNewRouteImport } from './routes/billboards.new'
import { Route as BillboardsIdEditRouteImport } from './routes/billboards_.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBillboardsRoute = MyBillboardsRouteImport.update({
  id: '/my-billboards',
  path: '/my-billboards',
  getParentRoute: () => rootRouteImport,
} as any)
const BillboardsIdRoute = BillboardsIdRouteImport.update({
  id: '/billboards/$id',
  path: '/billboards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillboardsNewRoute = BillboardsNewRouteImport.update({
  id: '/billboards/new',
  path: '/billboards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillboardsIdEditRoute = BillboardsIdEditRouteImport.update({
  id: '/billboards_/$id/edit',
  path: '/billboards/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/my-billboards': typeof MyBillboardsRoute
  '/billboards/$id': typeof BillboardsIdRoute
  '/billboards/new': typeof BillboardsNewRoute
  '/billboards/$id/edit': typeof BillboardsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/my-billboards': typeof MyBillboardsRoute
  '/billboards/$id': typeof BillboardsIdRoute
  '/billboards/new': typeof BillboardsNewRoute
  '/billboards/$id/edit': typeof BillboardsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/my-billboards': typeof MyBillboardsRoute
  '/billboards/$id': typeof BillboardsIdRoute
  '/billboards/new': typeof BillboardsNewRoute
  '/billboards_/$id/edit': typeof BillboardsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/my-billboards'
    | '/billboards/$id'
    | '/billboards/new'
    | '/billboards/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/my-billboards'
    | '/billboards/$id'
    | '/billboards/new'
    | '/billboards/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/my-billboards'
    | '/billboards/$id'
    | '/billboards/new'
    | '/billboards_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  MyBillboardsRoute: typeof MyBillboardsRoute
  BillboardsIdRoute: typeof BillboardsIdRoute
  BillboardsNewRoute: typeof BillboardsNewRoute
  BillboardsIdEditRoute: typeof BillboardsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-billboards': {
      id: '/my-billboards'
      path: '/my-billboards'
      fullPath: '/my-billboards'
      preLoaderRoute: typeof MyBillboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billboards/$id': {
      id: '/billboards/$id'
      path: '/billboards/$id'
      fullPath: '/billboards/$id'
      preLoaderRoute: typeof BillboardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billboards/new': {
      id: '/billboards/new'
      path: '/billboards/new'
      fullPath: '/billboards/new'
      preLoaderRoute: typeof BillboardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billboards_/$id/edit': {
      id: '/billboards_/$id/edit'
      path: '/billboards/$id/edit'
      fullPath: '/billboards/$id/edit'
      preLoaderRoute: typeof BillboardsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  MyBillboardsRoute: MyBillboardsRoute,
  BillboardsIdRoute: BillboardsIdRoute,
  BillboardsNewRoute: BillboardsNewRoute,
  BillboardsIdEditRoute: BillboardsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
